### ISSUE TITLE
 20160814_24_Shadsk - The title does not meet the requirements

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1068]
Steps To Reproduce:

1. Open https://test.long-travel.live/20160814_24_Shadsk/
2. Check that the content title is appropriate

Actual result: Світязь, Шацькі Озера
Expected result: Шацькі Озера, Волиньска область 

<img width="1440" alt="Снимок экрана 2022-08-11 в 3 55 51 PM" src="https://user-images.githubusercontent.com/110661667/184141307-e6f9aef5-b803-4c07-b917-112d65528e30.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
not fixed, pay attention to the expected result

**Comment by scholokov** [comment]
please retest
if issue still exist - please add new screenshot

**Comment by LesiaBezukh** [comment]
Still reproduce, please check again the expected result.
<img width="1440" alt="Снимок экрана 2022-08-12 в 3 54 46 PM" src="https://user-images.githubusercontent.com/110661667/184358459-410f1250-864c-4fe9-93de-a4ee24de95a2.png">

**Comment by scholokov** [comment]
мы можем писать - still reproduce, в случае когда у нас идентичный баг
в данном случае это другой баг
