### ISSUE TITLE
20140616_0707_greece - In the post-info  the publication date doesn't match the start date of the trip 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1106]
Steps To Reproduce: 

1. Open https://www.long-travel.live/20140616_0707_greece/
2. Pay attention to the date of a travel publication 

Actual result: 06.06.2014
Expected result: 16.06.2014

<img width="1440" alt="Снимок экрана 2022-08-17 в 3 27 39 PM" src="https://user-images.githubusercontent.com/110661667/185134582-6416b9fb-c91c-44b1-a507-29700bd55b3b.png">
<img width="1440" alt="Снимок экрана 2022-08-17 в 3 54 39 PM" src="https://user-images.githubusercontent.com/110661667/185137687-1e6bae07-df46-4a64-9a03-5313e20578ff.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Still reproduce

<img width="1440" alt="Снимок экрана 2022-08-22 в 4 18 13 PM" src="https://user-images.githubusercontent.com/110661667/185930788-7a69a6be-709a-4266-bcf8-3fb76b436ae8.png">

**Comment by GeorgiiZ90** [comment]
https://test.long-travel.live/20140616_0707_greece/
check on this link
