### ISSUE TITLE
20091026_1102_Toronto/ ND Date format at block "Hotel" doesn't meet the requirements

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1259]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Scroll down the page to the hotel block.
3. Pay attention to the date format at block "Hotel"

Actual result:
Date format at block "Hotel" doesn't meet the requirements
26.10-02.11.2009
Expected result:
26.10.2009 - 02.11.2009

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_11](https://user-images.githubusercontent.com/94845943/191034037-27c7bc24-fd7e-4461-9492-9af85ea416f5.png)
![Screenshot_12](https://user-images.githubusercontent.com/94845943/191034076-b254d840-8ee6-4488-bb38-5a906c420108.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
> fixed

not fixed yet
![Screenshot_11](https://user-images.githubusercontent.com/94845943/191742430-c1c42907-520c-4abe-acb5-87fcbe38c484.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
> fixed

Verified
