### ISSUE TITLE
20141102_10_Egypt_Hurghada no flag of country in Travel block in Header

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/long-travel-2#1463]
**STR:**
1.Open https://test.long-travel.live/20141102_10_Egypt_Hurghada/
2.Pay your attention to right side of Travel block

**Actual result:**
Flag of country doesn't included to preview of travel block at opposite side of name of travel.  

**Expected result:**
Flag of country included to preview of travel block at opposite side of name of travel.  

**Environment:**
Operating system: Windows 10 Pro
Browser: Google Chrome 106.0.5249.119 (64 bit)
![flag2](https://user-images.githubusercontent.com/92167884/195803356-38b76394-549a-4e63-9c95-927dd1412aba.png)

**Comment by scholokov** [comment]
fixed

**Comment by Xalep4ik** [comment]
still reproduce
![rep](https://user-images.githubusercontent.com/92167884/196149790-4b85943c-507c-4b9a-bc06-2a6ce798af0b.png)

**Comment by scholokov** [comment]
fixed
