### ISSUE TITLE
20210510_stariy_solvin/ Travels. Med size image with Title - unexpected element at image title (Uncategorized)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1863]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the page down - until finding med size image with Title  - Старий Солотвін
3)  Pay attention to travel's category

Actual Result: unexpected element - Uncategorized

Expected Result: no element

![Screenshot_1](https://user-images.githubusercontent.com/114935450/205702842-95b4634e-e457-42a1-9194-774be3e75fa4.png)

**Comment by scholokov** [comment]
fixed

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo краще вкажіть, що дефект відтворється, і додайте скрін дефекту

**Comment by MarynaChurylo** [comment]
bug still reproduced 

![Screenshot_4](https://user-images.githubusercontent.com/114935450/206695046-c021899c-1514-44f9-8991-e3e78ad45e7d.png)

**Comment by scholokov** [comment]
please retest

**Comment by MarynaChurylo** [comment]
successful
