### ISSUE TITLE
Wiki/ 4.2 Travels.List (084 travel) - misspelling name at travel's ID

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1886]
Steps:

1)  Open page https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List
2) Scroll the page to 084 travel 
3) Pay attention to ID (20210510_stariy_solvin)

Actual Result:    ID - 20210510_stariy_solvin
Expected Result: ID - 20210510_staryi_solotvyn

![Screenshot_4](https://user-images.githubusercontent.com/114935450/206266081-3ddf5a08-b237-4ead-a324-a8213a15e6fb.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
The bug is still reproduce

![Screenshot_2](https://user-images.githubusercontent.com/114935450/213300463-f5669d2d-437f-44ab-841b-f9c590741f70.png)

**Comment by MarynaChurylo** [comment]
the bug is still reproduce

Actual Result: ID - 20210510_stariy_solvin
Expected Result: ID - 20210510_staryi_solotvyn

![Screenshot_2](https://user-images.githubusercontent.com/114935450/214872902-2dc6467f-9f96-4746-a4cb-c6e8004f646c.png)

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo додайте наступні поля 

![Image](https://user-images.githubusercontent.com/88647733/230161647-c9786239-02fe-4990-996f-4cc444280942.png)

**Comment by GNatala** [comment]
Додано

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
