### ISSUE TITLE
20160710_0807_italy_odessa/The locality name is missed in the block "Black Sea" (Чорне море)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3307]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block Black Sea (Чорне море).

3. Pay attention to the absence of a locality name in the left side of the block.

**Actual result:**
The locality name is missed in the block "Black Sea" (Чорне море)

**Expected result:**
The locality name must be in the block "Black Sea" (Чорне море)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks#beach

![Image](https://user-images.githubusercontent.com/125134112/225296625-49d45cd8-b391-4b25-a9bf-7a81eee7e4bf.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/225296738-301fc7b3-78a8-48f9-ba78-a2d4deafd4bc.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @ABatalov The bug is not fixed


![Image](https://user-images.githubusercontent.com/125134112/226405537-bf041720-e21b-4f88-8d8d-11d2d1421147.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
