### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in Home block is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3310]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to Home block.
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine is 16x11 px

**Expected result:**
The size of the flag of Ukraine is 28x18 px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Graphical requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=344%3A13&t=Z9tJ803tdjqTWnmE-0

![Image](https://user-images.githubusercontent.com/125134112/225583952-535a4bdf-5fde-4179-a0a2-489863c5f9a4.png)

**Attachments:**

![Image](https://user-images.githubusercontent.com/125134112/225585851-1e8fed8e-1a67-4fa9-b356-dcc482f2e251.png)

**Comment by DmytroMarkulych** [comment]
@prokopenkoga1977 

![Image](https://user-images.githubusercontent.com/88647733/225631437-2058e8cd-56c6-44a4-9f11-3fc6109154f6.png)

**Comment by prokopenkoga1977** [comment]
@DmytroMarkulych виправив

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @ABatalov The bug is not fixed. No flag of Ukraine in the Home block


![Image](https://user-images.githubusercontent.com/125134112/226472384-b4d8c52c-fb40-4f0a-ac2b-715df1885f23.png)

**Comment by scholokov** [comment]
оновлені вимоги
прапорець там непотрібен
https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks

**Comment by prokopenkoga1977** [comment]
Passed
