### ISSUE TITLE
20150919_Kiev_Aviation_Museum/The Publication date of the travel the font is "Open Sans"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3500]
Steps to reproduce:
1. Open https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the Publication date in the footer.
3. Open DevTools.
4. Сheck font of the Publication date.

Actual result: the font is "Open Sans"
Expected result: the font is "Rubik"

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/234020231-26e52423-3d03-478f-8b4c-80c5a056c6a4.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue still exists
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c9774065-e59a-424a-8a91-39dc49dd7d3c)
