### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the Museum  block the Font-family of name is "Open Sans"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3552]
Steps to reproduce:
1. Open page https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the Name of the Museum block 
3. Open DevTools
4. Сheck font-family of the Museum name

Actual Result: Font-family: "Open Sans"
Expected Result: Font-family: 'Amazing Slab Trial'

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=X5E4OU3pwV3L8gKK-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/235887067-a9fbb32d-47ac-4e4a-a87c-ed0732eb1bc7.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue still exists
![image](https://github.com/scholokov/long-travel-2/assets/123776698/8f9e9733-089d-44d7-ad51-98ec5d8a8f04)
