### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the Museum block the Font-family of the Date is "Open Sans"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3554]
Steps to reproduce:

1. Open page https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the Date of the Museum block
3. Open DevTools
4. Сheck font-family of the Date of the Museum block

Actual Result: Font-family: "Open Sans"
Expected Result: Font-family: 'Rubik'

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=X5E4OU3pwV3L8gKK-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/235889744-223bdc2f-c4c3-4bb1-8005-905cef7f3777.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue still exists
![image](https://github.com/scholokov/long-travel-2/assets/123776698/878db435-97a3-4c0d-8f6b-5af570afab33)
