### ISSUE TITLE
20170709_protsiv/In the Footer block the Publication date of the travel the Font is "Open Sans"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3581]
**Steps to reproduce:**

1. Open page https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the Publication date of the Footer block
3. Open DevTools
4. Сheck font-family of the Publication date  of the Footer

**Actual Result**: Font-family: "Open Sans"
**Expected Result**: Font-family: 'Rubik'

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=X5E4OU3pwV3L8gKK-0

**Environment:**
Windows 10 Pro,
Opera v 96.0.4693.80

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/123776698/96b6b2a8-728e-4a66-b9cf-26913ef32fd0)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue still exists
![image](https://github.com/scholokov/long-travel-2/assets/123776698/86a0304c-a380-4ef6-bbb9-34ea8cc3972b)
