### ISSUE TITLE
20170709_protsiv/ Under the Map, the Standard block does not meet the requirements

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3685]
Steps to reproduce:

1. Open https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the structure block Under the Map

Actual Result: the Standard block does not meet the requirements
Expected Result: the Standard block meets the requirements

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.3-Подорож.-Стандартні-блоки

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/ad0ccaa6-a219-4963-8e5f-65d3017b40d5)

**Comment by ODrobik** [comment]
#3235

**Comment by DmytroMarkulych** [comment]
@ODrobik актуальний та очікуваний результати одинакові

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue still exists
![image](https://github.com/scholokov/long-travel-2/assets/123776698/0286b716-c44a-4c29-989d-f97166069cef)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
