### ISSUE TITLE
20170417_kiylov/The name of the fifteenth video gallery Страусина ферма is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3829]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the fifteenth video gallery of the Farm Kiylov Askania block.

3. Pay attention to the name of the fifteenth video gallery.

**Actual result:**
The name of the fifteenth video gallery Страусина ферма is in russian

**Expected result:**
The name of the fifteenth video gallery Страусина ферма is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/9152d591-2061-4405-bb39-5de0714e48e3)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/06189b1f-fd0b-49b7-8994-d9af0d2dfad1)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov The bug not fixed 

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/2c50f4cd-61f2-426f-ac76-8d581524be39)

**Comment by prokopenkoga1977** [comment]
Passed
