### ISSUE TITLE
20170417_kiylov/The name of the sixteenth video gallery Страусина ферма is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3830]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the sixteenth video gallery of the Farm Kiylov Askania block.

3. Pay attention to the name of the sixteenth video gallery.

**Actual result:**
The name of the sixteenth video gallery Страусина ферма is in russian

**Expected result:**
The name of the sixteenth video gallery Страусина ферма is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/7bb12bd4-337a-4774-833b-ce1e27d05403)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/9e589aa3-e4de-4410-8200-cec5ebaa2d99)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov  The bug not fixed 

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/e4b3578b-b82e-40be-a2f7-5fddd515b202)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
