### ISSUE TITLE
20170417_kiylov/The name of the twenty first video gallery Страусина ферма is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3835]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the twenty first video gallery of the Farm Kiylov Askania block.

3. Pay attention to the name of the  twenty first video gallery.

**Actual result:**
The name of the  twenty first video gallery Страусина ферма is in russian

**Expected result:**
The name of the twenty first video gallery Страусина ферма is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/9fa7c4dc-acc0-4e21-812b-d1393cdbe63e)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/8f411ad1-bf2a-4241-ad92-d40f09726f22)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov the bug not fixed

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/07934a05-d7f0-436b-8b96-31737bc85672)

**Comment by scholokov** [comment]
fixed
