### ISSUE TITLE
20200918_20_kharkiv Incorrect travel date

### ISSUE THREAD

**Issue by RChornyi** [scholokov/long-travel-2#424]
Steps to reproduce:
Open page https://test.long-travel.live/20200918_20_kharkiv

Actual result:
Travel date: 23.09.2021

Expected result:
Travel date: 18.09.2020

Environment:
iMac/macOS Catalina 10.15.7/Safari 15.2

<img width="1121" alt="Снимок экрана 2021-12-16 в 12 22 10" src="https://user-images.githubusercontent.com/90274131/146354118-fc2f8e72-1757-42a0-9e87-48fd579ab1ae.png">

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
а коментарий?

**Comment by RChornyi** [comment]
not fixed

<img width="1265" alt="Снимок экрана 2021-12-20 в 12 33 37" src="https://user-images.githubusercontent.com/90274131/146753924-1688617f-0c15-4ce7-9815-445f6b991078.png">

**Comment by scholokov** [comment]
fixed

**Comment by RChornyi** [comment]
verified
