### ISSUE TITLE
20170513_putivl_kruti/ The Standard "Дорога" block does not meet the requirements

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4275]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Pay attention to the structure Standard "Дорога" block on the page of the travel

Actual Result: The Standard "Дорога" block does not meet the requirements
Expected Result: The Standard "Дорога" block is meet the requirements

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/73235714-6fa1-4e9f-a1d4-32e4855baf9a)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue is still
![image](https://github.com/scholokov/long-travel-2/assets/123776698/dd46b75b-57a2-4239-98f2-86cc028357fb)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue is still
![image](https://github.com/scholokov/long-travel-2/assets/123776698/a00e5fd0-55f5-47f6-8093-51e14f657432)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
