### ISSUE TITLE
20180804_piryatin_mirgorod/Block "АЗС, де знімали фільм...": the font family of 2nd line is Rubik #3437

### ISSUE THREAD

**Issue by Gayane2610** [scholokov/long-travel-2#4335]
**Steps to reproduce:**
Open https://test.long-travel.live/20180804_piryatin_mirgorod
Scroll dawn to standard block

**Actual result:**
The font family of 2nd line of title is **Rubik**

**Expected result:**
The font family of 2nd line of title is **Amazing Slab Trial**

**Requirements:**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=VmgoMYZ0NBkyQn4b-0

**Environment**:
 MacBook Pro 13
Google Chrome 115.0.5790.170
<img width="1326" alt="Снимок экрана 2023-09-06 в 19 02 09" src="https://github.com/scholokov/long-travel-2/assets/139360116/f598e64b-11fb-40f2-9fdf-67a6e6b6db4c">

**Comment by scholokov** [comment]
fixed

**Comment by Gayane2610** [comment]
The bug still appears

![Image](https://github.com/scholokov/long-travel-2/assets/139360116/fc2c0124-dd4f-4d9f-bd01-2601716cc7e0)

**Comment by poroskundenys** [comment]
готово

**Comment by Gayane2610** [comment]
Tested
