### ISSUE TITLE
20180804_piryatin_mirgorod/ Standard block "Дорога": the title of block doesn't correspond to requirements #3437

### ISSUE THREAD

**Issue by Gayane2610** [scholokov/long-travel-2#4341]
**Steps to reproduce:**
Open https://test.long-travel.live/20180804_piryatin_mirgorod
Scroll dawn to standard block

**Actual result:**
The title of block is "Дорога: Пирятин-Миргород.    
                                   04.08.2018"

**Expected result:**
The title of block is "Дорога
                                   Пирятин-Миргород    
                                   04.08.2018"

**Requirements:**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=UPPgfeBFDwsxjzmp-0

**Environment:**
 MacBook Pro 13
Google Chrome 115.0.5790.170
<img width="1322" alt="Снимок экрана 2023-09-07 в 15 40 25" src="https://github.com/scholokov/long-travel-2/assets/139360116/5f690124-a56f-415c-a8fe-38f8d563e1a6">

**Comment by scholokov** [comment]
fixed

**Comment by Gayane2610** [comment]
The bug still appears

![Image](https://github.com/scholokov/long-travel-2/assets/139360116/2e17f32c-bfb9-4b0b-885f-b8e08ab42376)

**Comment by scholokov** [comment]
fixed

**Comment by Gayane2610** [comment]
Tested
