### ISSUE TITLE
20180804_piryatin_mirgorod/Standard block "Миргород": on title appears line "Полтавська область, Україна" #3437

### ISSUE THREAD

**Issue by Gayane2610** [scholokov/long-travel-2#4343]
**Steps to reproduce:**
Open https://test.long-travel.live/20180804_piryatin_mirgorod
Scroll dawn to standard block

**Actual result:**
On title of standard block appears line "Полтавська область, Україна"

**Expected result:**
On title of standard block doesn't appear line "Полтавська область, Україна"

**Requirements:**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=UPPgfeBFDwsxjzmp-0

**Environment:**
 MacBook Pro 13
Google Chrome 115.0.5790.170
<img width="1296" alt="Снимок экрана 2023-09-07 в 16 23 19" src="https://github.com/scholokov/long-travel-2/assets/139360116/3a5cc9f6-965d-4d23-b1eb-cd418e816537">

**Comment by scholokov** [comment]
fixed

**Comment by Gayane2610** [comment]
The bug still appears

![Image](https://github.com/scholokov/long-travel-2/assets/139360116/8287c059-36e8-4ab6-b673-5e69d5f85171)

**Comment by scholokov** [comment]
fixed

**Comment by Gayane2610** [comment]
Tested
