### ISSUE TITLE
20180428_0501_beregovo/Preview photo: the date format is DD.MM-DD.MM.YYYY #3432

### ISSUE THREAD

**Issue by Gayane2610** [scholokov/long-travel-2#4408]
**Steps to reproduce:**
Open https://test.long-travel.live/20180428_0501_beregovo
Pay attention on preview photo

**Actual result:**
The date format is **DD.MM-DD.MM.YYYY** (28.04-01.05.2018)

**Expected result:**
The date format is **DD.MM.YYYY-DD.MM.YYYY**(28.04.2018-01.05.2018)

**Requirements**:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment**:
 MacBook Pro 13
Google Chrome 115.0.5790.170
<img width="1317" alt="Снимок экрана 2023-09-14 в 18 06 48" src="https://github.com/scholokov/long-travel-2/assets/139360116/0e47db21-9030-4427-aa3b-efde4687b5ba">

**Comment by scholokov** [comment]
fixed

**Comment by Gayane2610** [comment]
The bug still appears: the format of date doesn't correspond to the requirements

![Image](https://github.com/scholokov/long-travel-2/assets/139360116/8537a6b2-063e-4ea9-87f0-3335380f7026)

**Comment by scholokov** [comment]
fixed

**Comment by Gayane2610** [comment]
Tested
