### ISSUE TITLE
20170521_korosten / The tag "Lazy" is instead of the tag "Військовий об'єкт" in the Preview

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4485]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the tag "Lazy" in the Preview.

**Actual Result:** 
The tag "Lazy" is instead of the tag "Військовий об'єкт".

**Expected Result:** 
The  tag "Військовий об'єкт" is in the Preview.

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/d93bf69d-0ccf-4d8c-b6a5-d4b5e7c2957b)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue still exists

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/e4b5b13e-38d2-444d-acd7-5520f4f16fc2)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
