### ISSUE TITLE
20170513_putivl_kruti/The Preview is not displayed in the "Museum" Standard block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4573]
Steps to reproduce:

1. Open: https://long-travel.live/20170513_putivl_kruti/
2. Scroll down to the "Museum" Standard block
3. Pay attention to the Preview of the "Museum" Standard block

Actual Result:The Preview is not displayed in the "Museum" Standard block

Expected Result: The Preview is displayed in the "Museum" Standard block

Environment:
Windows 10 Pro (x64),
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c62aaec4-9437-4e9e-970e-a27a57f720b2)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue is still 

![Image](https://github.com/scholokov/long-travel-2/assets/123776698/27bc916c-9fe0-4545-a418-e8e53ea9ccca)

**Comment by scholokov** [comment]
please retest
already fixed

**Comment by ODrobik** [comment]
verified
