### ISSUE TITLE
20170513_putivl_kruti/ The Flag of the country is not displayed in the Standard "Музей" block 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4574]
Steps to reproduce:

1. Open https://long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the Standard "Музей" block after 2nd Standard "Дорога" block
3. Pay attention to the absence of a flag in the Standard "Музей" block

Actual Result: The Flag of the country is not displayed in the Standard  "Музей"  block

Expected Result: The Flag of the country is displayed in the Standard "Музей"  block

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/38abee5c-d2b9-48ad-aae6-57cbb1666ddb)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
issue is still 

![Image](https://github.com/scholokov/long-travel-2/assets/123776698/e64301c5-b9b6-49ac-893e-005115a3fa67)

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
verified
