### ISSUE TITLE
20210403_zagaltsy_Incorrect travel name

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#667]
**Description:**
The name of the city on the travel page does not meet the requirements of the project.

**Steps to reproduce:**
1. Open page [](https://test.long-travel.live/20210403_zagaltsy/)
2. Pay attention to what language the name of the city is indicated.

**Actual result:**
On the travel page, the name of the city is indicated in English.

**Expected result:**
The name of the trip must be in the language of the country to which the city belongs.

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64 bit)

![имя](https://user-images.githubusercontent.com/105543094/169596805-618e1a05-13c0-4906-ade2-62c9c5a1f8eb.png)

**Comment by scholokov** [comment]
Actual result:
On the travel page, the name of the city is indicated in English.

в экшуале не должно быть "где"

**Comment by KaterinaNimenko35** [comment]
@scholokov   corrected

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
@scholokov   @GeorgiiZ90     bug not fixed, the error is reproduced


![апрлдл](https://user-images.githubusercontent.com/105543094/170268491-e6c1e705-8bcb-46ed-a2c9-484092777d9b.png)

**Comment by scholokov** [comment]
не забываем менять статус бага.
в статусе "ready for testing" его никто не найдет

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
@GeorgiiZ90    an issue is reproduced


![2022-05-30 10 35 51](https://user-images.githubusercontent.com/105543094/170942360-f36a1b41-f51a-4ef4-9918-827d2d78e70e.png)



![апрлдл](https://user-images.githubusercontent.com/105543094/170942514-8c65894a-36a0-4e8c-b8c7-1d8563d06352.png)

**Comment by KaterinaNimenko35** [comment]
@GeorgiiZ90    an issue is reproduced

![2022-05-31 22 32 41](https://user-images.githubusercontent.com/105543094/171273263-624be6aa-b525-434a-9799-c0a52907e2f0.png)


![111ааа](https://user-images.githubusercontent.com/105543094/171273467-57c2780f-ba5d-429d-b05a-05c14c69f326.png)

**Comment by KaterinaNimenko35** [comment]
@GeorgiiZ90    an issue is reproduced


![2022-06-01 21 21 04](https://user-images.githubusercontent.com/105543094/171476441-8fe04018-27fb-49b6-bbf3-1e5101dd87ba.png)


![2022-05-25 15 47 59123](https://user-images.githubusercontent.com/105543094/171476496-af8a4660-8dd0-467e-9a5b-3a4b45f9b024.png)

**Comment by KaterinaNimenko35** [comment]
verified

**Comment by KaterinaNimenko35** [comment]
an issue is reproduced

![2022-06-08 15 13 09](https://user-images.githubusercontent.com/105543094/172613980-8e3fa83c-f7a0-4aca-9927-2c279008e3a6.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
verified
