### ISSUE TITLE
20210403_zagaltsy_ Spacing between photos does not meet the requirement.

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#668]
**Description:**
The horizontal padding between photos in the gallery on the travel page does not meet the requirements.
Photo alignment to the bottom edge of the gallery block does not meet the requirements.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/20210403_zagaltsy/ 
2. Scroll the page to the photo gallery block.
3. Pay attention to the horizontal indents between the photos.

**Actual result:**
Horizontal padding between photos on the travel page is not the same size.
Photo alignment to the bottom edge of the gallery block page is displayed incorrectly.

**Expected result:**
Horizontal indents between photos in the gallery block must be the same.
Photo alignment on the bottom edge of the gallery block should be the same.

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64 bit)

![0](https://user-images.githubusercontent.com/105543094/169651243-9390479a-1f73-4796-affa-33dda882263b.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
@scholokov   @GeorgiiZ90     bug not fixed, the error is reproduced

**Comment by KaterinaNimenko35** [comment]
@GeorgiiZ90   an issue is reproduced


![2022-05-30 10 45 30](https://user-images.githubusercontent.com/105543094/170944923-58c6000f-55e2-4e2d-8019-2011a2c311fa.png)

**Comment by GeorgiiZ90** [comment]
Fixed

**Comment by KaterinaNimenko35** [comment]
@GeorgiiZ90   an issue is reproduced

**Comment by scholokov** [comment]
в идеале для подтверждения воспроизведения ошибки атачить новый скрин

**Comment by KaterinaNimenko35** [comment]
@scholokov 
@GeorgiiZ90   an issue is reproduced


![2022-06-01 16 47 43](https://user-images.githubusercontent.com/105543094/171421098-aa5c59bc-639b-4151-bb9b-f6f332144186.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
an issue is reproduced

**Please, pay attention:**
1. There is no issue in the screenshot of the scrolling screen, which was taken through the Google Chrome developer menu.
2. In the screenshot through a third-party application -an issue is reproduced.
3. When you open the page http://www.test.long-travel.live/20210403_zahaltsi/ an issue is reproduced.

![2022-06-10 10 03 19](https://user-images.githubusercontent.com/105543094/173009966-768f3a90-2454-46da-a0cf-269d08084789.png)


![2022-06-10 09 37 43](https://user-images.githubusercontent.com/105543094/173010043-3b05fede-d562-4025-bf6f-208024db9404.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
verified
