### ISSUE TITLE
20220124_28_netherlands: Footer _ Publication date not specified

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#742]
**Description:**
The publication date of the Trip is missing in the Footer block. According to the requirements it must be present.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/20220124_28_netherlands/
2. Scroll down to the Footer block
3. Pay attention to the absence of the date of publication of the Trip at the end of the page.

**Actual result:**
The publication date of the Trip is **missing** in the Footer block. 

**Expected result:**
The publication date of the Trip is **present** in the Footer block. 
![3](https://user-images.githubusercontent.com/105114364/172068142-d9669431-5f44-4e7a-b4d2-db929dff3b53.jpg)

**Environment:**
Operating system Windows 10 Pro
Browser Google Chrome 102.0.5005.6 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#622

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
issue is still reproduced
![1](https://user-images.githubusercontent.com/105114364/173830807-01b2c8b9-fe27-4275-a02f-9d3420c0d92b.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
verified
