### ISSUE TITLE
20220124_28_netherlands: Footer _ Travel category not specified

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#743]
**Description:**
The travel category is missing in the Footer block. According to the requirements it must be present.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/20220124_28_netherlands/
2. Scroll down to the Footer block
3. Pay attention to the absence of the travel category at the end of the page

**Actual result:**
The travel category **is missing** in the Footer block.

**Expected result:**
The travel category **is present** in the Footer block.

![4](https://user-images.githubusercontent.com/105114364/172068359-cbb0fbf4-c966-4397-990b-0f8401d9abc0.jpg)

**Environment:**
Operating system Windows 10 Pro
Browser Google Chrome 102.0.5005.6 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#622

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
issue is still reproduced
![1](https://user-images.githubusercontent.com/105114364/173830947-c1d9a26e-1cfa-46d4-9562-2f030164e36f.png)

**Comment by scholokov** [comment]
outdated

**Comment by KaterinaNimenko35** [comment]
The bug is not relevant
Design outdated
