### ISSUE TITLE
20130908_tropical_park - block data and block No Responses - dark font

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#864]
Steps to reproduce:
1,Open https://test.long-travel.live/20130908_tropical_park/
2,Scroll down

Actual result:
dark font

Expected result:
light font

![2022-07-11 19_53_20-](https://user-images.githubusercontent.com/105969368/178318110-b968e008-95bd-4c50-b99e-067ddb8fcea1.png)

![2022-07-11 19_52_29-Window](https://user-images.githubusercontent.com/105969368/178318133-538d60cb-e220-4f78-8057-5b8ee645a894.png)

![2022-07-11 19_54_46-Window](https://user-images.githubusercontent.com/105969368/178318165-42ebf2ca-71df-4c8c-8a14-16af222c2e5f.png)

![2022-07-11 19_57_58-Window](https://user-images.githubusercontent.com/105969368/178318185-86e1b01c-51e9-4d01-8bd6-d6d2682f33cd.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)
Screen resolution: 1600 x 900

OS: iOS, v15.3
Browser: Chrome
Resolution: 1170 x 2532 px

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
**Please pay attention to:**
1. The bug is written in an outdated design but is partially fixed: **Header - Временной период - light font**
2. An identical bug has been written #937

**Close bug as:**
1. The bug is not relevant. Design outdated
2. The bug is duplicated
4. Bug fixed

**Comment by KaterinaNimenko35** [comment]
verified
